#!/usr/bin/env python3
"""
manhwa.py -- the production CLI for AI-assisted manhwa / webtoon pipelines.

  init      scaffold a project (blank or from the reference pilot)
  prompts   emit a per-tool prompt pack + machine-readable job queue
  assemble  panels -> vertical strip -> platform tiles + manifest + preview
  check     run the QC gates on the script and the assembled strip
  status    where the production stands and what to do next
  plan      staggered weekly production calendar (studio logic)

Everything is plain JSON + PNG on disk. No server, no database, no lock-in.
Docs: ../../references/   Repo guide: ../../../docs/02-pipeline-step-by-step.md
"""
from __future__ import annotations

import argparse
import json
import os
import shutil
import sys
from datetime import date
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

from manhwa_lib import demo as demo_mod          # noqa: E402
from manhwa_lib import layout as layout_mod      # noqa: E402
from manhwa_lib import project as proj           # noqa: E402
from manhwa_lib import prompts as prompts_mod    # noqa: E402
from manhwa_lib import qc as qc_mod              # noqa: E402
from manhwa_lib.project import TEAM_PRESETS     # noqa: E402
from manhwa_lib.specs import PLATFORM_SPECS, VERSION, resolve_platform  # noqa: E402

# --------------------------------------------------------------------------- #
# pretty output
# --------------------------------------------------------------------------- #
_TTY = sys.stdout.isatty()


def c(s, code):
    return f"\033[{code}m{s}\033[0m" if _TTY else s


def ok(s):   return c(s, "32")
def warn(s): return c(s, "33")
def err(s):  return c(s, "31")
def dim(s):  return c(s, "90")
def bold(s): return c(s, "1")


def hr(title=""):
    line = "─" * max(0, 66 - len(title))
    print(bold(f"\n{title} {line}") if title else "─" * 68)


# --------------------------------------------------------------------------- #
# commands
# --------------------------------------------------------------------------- #
def cmd_init(a):
    root = Path(a.dir)
    if root.exists() and any(root.iterdir()) and not a.force:
        print(err(f"{root} is not empty (use --force)"))
        return 2
    proj.scaffold(root, a.title or root.name, a.platform, a.lang)
    chars = 0
    if a.demo:
        _write_demo_content(root)
        chars = len(demo_mod.CHARACTERS)
    spec = resolve_platform(a.platform)
    hr("project created")
    print(f"  {bold(str(root))}")
    print(f"  platform   {spec['label']}  ({spec['width']}px wide, {spec['tile_max_h']}px tiles)")
    print(f"  characters {chars}" + ("" if chars else dim("  (add characters/<id>.json)")))
    print()
    print("next:")
    print(f"  python manhwa.py prompts episodes/ep001.json --tool sdxl")
    print(f"  python manhwa.py assemble episodes/ep001.json")
    print(f"  python manhwa.py check episodes/ep001.json --final")
    return 0


def _write_demo_content(root: Path):
    proj.save_json(root / "series.json", demo_mod.SERIES)
    for cid, c in demo_mod.CHARACTERS.items():
        proj.save_json(root / "characters" / f"{cid}.json", c)
    proj.save_json(root / "episodes" / "ep001.json", demo_mod.EPISODE)
    (root / "README.md").write_text(
        "# NEON ARCHIVE\n\nReference pilot project generated by `manhwa.py demo`.\n"
        "Story data lives in `series.json`, `characters/`, `episodes/`. Art goes in `art/`.\n",
        encoding="utf-8")


def cmd_demo(a):
    root = Path(a.dir)
    root.mkdir(parents=True, exist_ok=True)
    _write_demo_content(root)
    p = proj.Project(root)
    _, ep = p.episode(1)
    print(bold(f"\nbuilt reference pilot in {root}"))
    man = layout_mod.assemble(p, 1, ep, layout_mod.Options(annotate=a.annotate))
    res = qc_mod.run_checks(p, 1, ep, man, qc_mod.load_outputs(root / "output" / "ep001")[1])
    _print_qc(res)
    print(dim(f"\npreview: {root}/output/ep001/preview.html"))
    return 0 if res["ok"] else 1


def cmd_status(a):
    p = proj.Project(_root(a))
    plat = p.platform
    chars = p.characters()
    hr(p.series.get("title", "project"))
    print(f"  {dim('root')}      {p.root}")
    print(f"  {dim('platform')}  {plat['label']}  {plat['width']}px wide / {plat['tile_max_h']}px tiles")
    print(f"  {dim('schedule')}  {p.series.get('release_schedule','-')}   language {p.series.get('release_language','-')}")
    print(f"  {dim('cast')}      {', '.join(chars) if chars else warn('none yet')}")

    eps = p.episodes()
    if not eps:
        print(warn("\n  no episodes yet -- create episodes/ep001.json"))
        return 0
    hr("episodes")
    print(f"  {'ep':<5} {'title':<26} {'panels':>7} {'art':>7} {'tiles':>6} {'state':<10}")
    pending = []
    for path in eps:
        ep = proj.load_json(path)
        no = int(ep.get("episode", 0))
        panels = ep.get("panels", [])
        art = sum(1 for x in panels if p.panel_image_path(no, x.get("id", ""), x.get("image")))
        man_path = p.root / "output" / f"ep{no:03d}" / "manifest.json"
        man = proj.load_json(man_path) if man_path.exists() else None
        state = "published" if ep.get("status") == "published" else (
            "assembled" if man else ("art" if art == len(panels) and panels else "scripted"))
        colour = ok if art == len(panels) and panels else (warn if art else dim)
        print(f"  {no:<5} {str(ep.get('title',''))[:26]:<26} {len(panels):>7} "
              f"{colour(f'{art:>3}/{len(panels):<3}')} {(man or {}).get('tile_count', '-'):>6} {state:<10}")
        if not panels:
            continue
        if art < len(panels):
            pending.append(f"generate {len(panels)-art} panel(s) for ep{no:03d} -> art/ep{no:03d}/")
        if art >= len(panels) and not man:
            pending.append(f"assemble ep{no:03d}")
        if man and art >= len(panels):
            pending.append(f"check ep{no:03d} --final  then upload output/ep{no:03d}/upload/")

    missing_refs = [cid for cid, c in chars.items()
                    if not any((p.root / r).exists() for r in (c.get("ref_images") or []))]
    if missing_refs:
        pending.insert(0, "generate character sheets first: " + ", ".join(missing_refs) +
                       "  (promptpack/<tool>-ep001.md)")
    if pending:
        hr("next actions")
        for i, t in enumerate(pending[:8], 1):
            print(f"  {i}. {t}")
    return 0


def cmd_prompts(a):
    p = proj.Project(_root(a))
    path, ep = p.episode(a.episode)
    ep_no = int(ep.get("episode", 1))
    res = prompts_mod.build_pack(p, ep_no, ep, tool=a.tool,
                                 include_sheets=not a.no_sheets, include_cover=not a.no_cover)
    (p.root / "art" / f"ep{ep_no:03d}").mkdir(parents=True, exist_ok=True)
    hr(f"prompt pack - {a.tool}")
    print(f"  {bold(str(res['entries']))} entries ({res['panels']} panels + sheets + cover)")
    for f in res["files"]:
        print(f"  {dim('->')} {f}")
    print(dim("\n  generate the character sheets first, approve them, then the panels."))
    return 0


def cmd_assemble(a):
    p = proj.Project(_root(a))
    _, ep = p.episode(a.episode)
    ep_no = int(ep.get("episode", 1))
    opts = layout_mod.Options(
        width=a.width, tile_height=a.tile_height,
        out_dir=Path(a.out) if a.out else None,
        no_art=a.no_art, no_letter=a.no_letter, annotate=a.annotate,
        format=a.format, quality=a.quality, bg=a.bg, tile_search=a.tile_search)
    man = layout_mod.assemble(p, ep_no, ep, opts)
    hr(f"assembled ep{ep_no:03d}")
    print(f"  strip     {man['width']} x {man['total_height']:,}px   {man['panels']} panels")
    print(f"  tiles     {man['tile_count']} x {man['tile_height_cap']}px cap   "
          f"{man['total_bytes']/1048576:.2f} MB total")
    print(f"  pacing    {man['est_read_screens']} phone screens   ~{man['est_read_seconds']/60:.1f} min read")
    if man["placeholders"]:
        print(warn(f"  {len(man['placeholders'])} placeholder panel(s): "
                   f"{', '.join(man['placeholders'][:6])}{'...' if len(man['placeholders'])>6 else ''}"))
    out = Path(a.out) if a.out else p.root / "output" / f"ep{ep_no:03d}"
    print(f"  {dim('out')}       {out}")
    print(f"  {dim('preview')}   {out}/preview.html")
    print(f"  {dim('upload')}    {out}/upload/   (see UPLOAD.md)")
    return 0


def _print_qc(res):
    symbols = {"error": err("✗ ERROR"), "warn": warn("! warn "), "info": dim("· info ")}
    hr(f"QC - {res['counts']['error']} errors, {res['counts']['warn']} warnings, {res['counts']['info']} notes")
    for f in res["findings"][:40]:
        where = dim(f"{f['where']}: ") if f["where"] else ""
        print(f"  {symbols[f['severity']]} {dim('['+f['code']+']')} {where}{f['message']}")
    if len(res["findings"]) > 40:
        print(dim(f"  ... {len(res['findings'])-40} more in the report file"))
    print()
    print("  " + (ok("GATE: PASS") if res["ok"] else err("GATE: FAIL")) +
          dim("   (no blocking errors)" if res["ok"] else "   (fix the errors before uploading)"))
    return res


def cmd_check(a):
    p = proj.Project(_root(a))
    _, ep = p.episode(a.episode)
    ep_no = int(ep.get("episode", 1))
    out_dir = Path(a.out) if a.out else p.root / "output" / f"ep{ep_no:03d}"
    man, lay = qc_mod.load_outputs(out_dir)
    res = qc_mod.run_checks(p, ep_no, ep, man, lay, final=a.final)
    if a.json:
        print(json.dumps(res, indent=2))
    else:
        _print_qc(res)
    rep = out_dir if out_dir.exists() else p.root / "reviews"
    rep.mkdir(parents=True, exist_ok=True)
    proj.save_json(rep / "qc-report.json", res)
    (rep / "qc-report.md").write_text(qc_mod.report_md(res, p), encoding="utf-8")
    if not a.json:
        print(dim(f"  report: {rep}/qc-report.md"))
    if not res["ok"]:
        return 1
    if a.strict and res["counts"]["warn"]:
        return 1
    return 0


def cmd_plan(a):
    p = proj.Project(_root(a))
    start = date.fromisoformat(a.start) if a.start else date.today()
    rows = proj.production_plan(a.episodes, a.team, start, a.cadence)
    hr(f"production plan - {a.episodes} episodes - {TEAM_PRESETS[a.team]['label']}")
    print(dim(f"  {TEAM_PRESETS[a.team]['lead_days']}-day lead per episode, staged so every week ships one.\n"))
    for row in rows:
        stages = "   ".join(f"ep{s['episode']}:{s['stage']}" for s in row["stages"])
        ship = ok(f"  SHIPS ep{row['ships']:03d}") if row.get("ships") else dim("  --")
        print(f"  wk{row['week']:>2} {row['date']} {ship}   {stages}")
    print()
    print(dim("  Rule of thumb: never publish from the leading edge of the plan. Launch with\n"
              "  3-4 finished episodes in the buffer (see docs/02-pipeline-step-by-step.md)."))
    return 0


def cmd_platforms(a):
    hr("platform specs")
    for key, s in PLATFORM_SPECS.items():
        note = "" if s["verified"] else warn("  (verify in your dashboard)")
        print(f"  {bold(key):<14} {s['width']:>5}px wide  {s['tile_max_h']:>6}px tiles  "
              f"{(s['tile_max_bytes'] or 0)/1048576:>4.0f}MB/tile  {'/'.join(s['formats'])}{note}")
        print(dim(f"                 {s['label']}"))
    return 0


# --------------------------------------------------------------------------- #
# parser
# --------------------------------------------------------------------------- #
def _root(a) -> Path:
    if getattr(a, "root", None):
        return Path(a.root).resolve()
    return proj.find_root(Path.cwd())


def build_parser():
    ap = argparse.ArgumentParser(prog="manhwa.py", description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--version", action="version", version=f"manhwa.py {VERSION}")
    sub = ap.add_subparsers(dest="cmd", required=True)

    def add_root(sp):
        sp.add_argument("-C", "--root", help="project root (folder containing series.json)")
        return sp

    s = add_root(sub.add_parser("init", help="scaffold a new project"))
    s.add_argument("dir")
    s.add_argument("--title")
    s.add_argument("--platform", default="webtoons", choices=sorted(PLATFORM_SPECS))
    s.add_argument("--lang", default="en")
    s.add_argument("--demo", action="store_true", help="also write the NEON ARCHIVE pilot episode")
    s.add_argument("--force", action="store_true")
    s.set_defaults(func=cmd_init)

    s = add_root(sub.add_parser("demo", help="build the reference pilot project end to end"))
    s.add_argument("dir", nargs="?", default="neon-archive")
    s.add_argument("--annotate", action="store_true")
    s.set_defaults(func=cmd_demo)

    s = add_root(sub.add_parser("status", help="production dashboard"))
    s.set_defaults(func=cmd_status)

    s = add_root(sub.add_parser("prompts", help="emit a prompt pack for one episode"))
    s.add_argument("episode", help="episode number or path to episodes/epNNN.json")
    s.add_argument("--tool", default="sdxl",
                   choices=prompts_mod.TOOLS + ["comfy"])
    s.add_argument("--no-sheets", action="store_true")
    s.add_argument("--no-cover", action="store_true")
    s.set_defaults(func=cmd_prompts)

    s = add_root(sub.add_parser("assemble", help="build strip + tiles + preview"))
    s.add_argument("episode")
    s.add_argument("--out")
    s.add_argument("--width", type=int, help="override output width (px)")
    s.add_argument("--tile-height", type=int, help="override tile height cap (px)")
    s.add_argument("--no-art", action="store_true", help="storyboard mode: draw placeholders, ignore art/")
    s.add_argument("--no-letter", action="store_true", help="skip bubbles (art-only pass)")
    s.add_argument("--annotate", action="store_true", help="burn panel id/shot/beat onto each panel")
    s.add_argument("--format", default="png", choices=["png", "jpg", "both"])
    s.add_argument("--quality", type=int, default=92)
    s.add_argument("--bg")
    s.add_argument("--tile-search", type=int, default=320,
                   help="how many px above the cap to hunt for an empty cut row")
    s.set_defaults(func=cmd_assemble)

    s = add_root(sub.add_parser("check", help="run the QC gates"))
    s.add_argument("episode")
    s.add_argument("--out", help="output folder to read manifest/layout from")
    s.add_argument("--final", action="store_true", help="treat missing art / placeholders as errors")
    s.add_argument("--strict", action="store_true", help="warnings also fail the gate")
    s.add_argument("--json", action="store_true")
    s.set_defaults(func=cmd_check)

    s = add_root(sub.add_parser("plan", help="staggered weekly production calendar"))
    s.add_argument("--episodes", type=int, default=8)
    s.add_argument("--team", default="solo", choices=sorted(TEAM_PRESETS))
    s.add_argument("--start", help="YYYY-MM-DD")
    s.add_argument("--cadence", default="weekly", choices=["weekly"])
    s.set_defaults(func=cmd_plan)

    s = sub.add_parser("platforms", help="show platform specs")
    s.set_defaults(func=cmd_platforms)
    return ap


def main(argv=None):
    ap = build_parser()
    a = ap.parse_args(argv)
    try:
        return a.func(a)
    except FileNotFoundError as e:
        print(err(f"error: {e}"))
        return 2
    except KeyError as e:
        print(err(f"error: {e}"))
        return 2


if __name__ == "__main__":
    sys.exit(main())
